src/ProjectManagementSystem/ProjectManagementSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('WebAPI.urls')),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url(r'^', include('WebUI.urls')),
]

src/ProjectManagementSystem/WebUI/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth.views import logout
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.index),
    url(r'^login/$', views.login_index, name="user_login"),
    url(r'^register/$', views.register_index, name ="register_index"),
    url(r'^forgot/$', views.forgotten_password, name="forgotten_password"),
    url(r'^reset/(?P<slug>[\w]+)/$', views.reset_password, name="reset_password"),
    url(r'^dashboard/$', views.dashboard_index),
    url(r'^profile/$', views.profile_index),
    url(r'^search$', views.search, name = "search"),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^project/new/$', views.new_project, name='new_project'),
    url(r'^dashboard/(?P<pk>[0-9]+)$', views.dashboard_project_view, name = 'project_index'),
    url(r'^dashboard/delete/(?P<pk>[0-9]+)/$', views.delete_state, name = 'delete_state'),
    url(r'^dashboard/tasks/$', views.dashboard_ticket_view,  name = 'dashboard_ticket_view'),
    url(r'^dashboard/tasks/new$', views.new_ticket_view,  name = 'new_ticket_view'),
    url(r'^project/settings$', views.project_settings_view,  name = 'project_settings'),
    url(r'^project/settings/users$', views.user_project_settings, name = 'user_project_settings'),
    url(r'^project/collaborators$', views.viewCollaborators, name = 'viewCollaborators'),
    url(r'^project/users/delete/(?P<slug>[\w_-]+)/$', views.remove_user_from_project, name = 'remove_user_from_project'),
    url(r'^project/delete$', views.delete_project, name = 'delete_project'),
    url(r'^project/tickets/detail/(?P<slug>[ \w_-]+)/$', views.ticket_detail, name = 'ticket_detail'),
    url(r'^project/tickets/detail/(?P<pk>[ \w_-]+)/comments/$', views.add_comment, name = 'add_comment'),
    url(r'^project/tickets/delete/(?P<id>[0-9]+)/$', views.delete_ticket, name = 'delete_ticket'),
    url(r'^project/tickets/changes/$', views.project_ticket_changes, name = 'project_ticket_changes'),
    url(r'^(?P<slug>[\w_-]+)/$', views.view_user_profile, name = 'view_user_profile'),
    url(r'^dashboard/board/(?P<pk>[0-9]+)$', views.update_board_display, name='update_board_display'),
    url(r'^dashboard/board/new$', views.new_board, name='new_board'),
    url(r'^dashboard/board/delete$', views.delete_board, name='delete_board'),
    url(r'^profile/update/$', views.updateUserDetails, name='updateUserDetails'),
    url(r'^profile/update/password$', views.updateUserPassword, name='updateUserPassword'),
    url(r'^project/calendar$', views.displayCalendar, name='displayCalendar'),
    url(r'^project/boards$', views.displayBoardSettings, name='displayBoardSettings'),
    url(r'^project/boards/states/update$', views.updateStateOrder, name='updateStateOrder'),
    url(r'^project/boards/states/new$', views.newState, name='newState'),
    url(r'^project/boards/states/copy/(?P<pk>[0-9]+)$', views.copyStateToSubBoard, name='copyStateToSubBoard'),
    url(r'^project/update$', views.update_project, name = 'update_project'),
]

src/ProjectManagementSystem/WebAPI/models.py
from django.db import models
from django.db.models.signals import post_save
from rest_framework.authtoken.models import Token
from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth.models import User
from WebAPI.choices import *
from datetime import datetime, date


#####
# use a signal to detect when a user has been created. When it is created, a unique Token should be allocated to this user
# for authentication purposes whenever they use the API.
#####
@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_authentication_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


class Project(models.Model):
    name = models.CharField(max_length=30)
    short_name = models.CharField(max_length=30, null = True, blank = True)
    owner = models.ForeignKey(User)
    visibility = models.BooleanField(default = False) #True for a public project, false for a private
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)

    def save(self, *args, **kwargs):
        if not self.short_name:
            self.short_name = self.name[0:2].upper()
        super(Project, self).save(*args, **kwargs)

class Board(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    default = models.BooleanField(default=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=40)

class State(models.Model):
    name = models.CharField(max_length=30)
    short_name = models.CharField(max_length = 5)
    order = models.IntegerField(blank = True, null = True, default = -1)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    projects = models.ManyToManyField(Project, blank=True, null=True)
    joined = models.DateTimeField(auto_now_add=True, blank=True, null = True)
    reset_password_hash = models.CharField(max_length = 50, blank = True, null=True)

class Ticket(models.Model):
    name = models.CharField(max_length=300)
    short_name = models.CharField(max_length=30, blank = True, null = True)
    description = models.TextField(blank = True, null = True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    last_modified = models.DateTimeField(auto_now = True)
    created_on = models.DateTimeField(auto_now_add=True)
    completed_on = models.DateTimeField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name="ticket_created_by")
    associated_users = models.ManyToManyField(User, related_name="associated_users")

    type = models.CharField(
        max_length=1,
        choices=TYPE_CHOICES,
        default=TYPE_CHOICES[0][0]
    )

    priority = models.CharField(
        max_length=1,
        choices=PRIORITY_CHOICES,
        default=PRIORITY_CHOICES[0][0],
    )

    assigned_to = models.ForeignKey(User, blank = True, null = True, related_name="ticket_assigned_to")
    state = models.CharField(
        max_length=5,
        choices=STATE_CHOICES,
        default=STATE_CHOICES[0][0],
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super(Ticket, self).save(*args, **kwargs)
        if not self.short_name:
            self.short_name = self.project.short_name + str(self.id)
            self.save()

        if self.state == 'C' and not self.completed_on:
            self.completed_on = datetime.now()
            self.save()

        elif self.state != "C" and self.completed_on:
            self.completed_on = None
            self.save()

class Invitation(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.EmailField()
    invitor = models.ForeignKey(User)
    issued = models.DateTimeField(auto_now_add=True, blank=True, null = True)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created_on',)

def project_directory_path(instance, filename):
    return settings.MEDIA_ROOT + 'documents/project_{0}/{1}'.format(instance.project.id, filename)

class Event(models.Model):
    event_title = models.CharField(max_length=255, default="Untitled")
    type = models.CharField(
        max_length=1,
        choices=EVENT_TYPE_CHOICES,
        default=EVENT_TYPE_CHOICES[0][0]
    )
    start_date = models.DateField()
    end_date = models.DateField()
    added_by = models.ForeignKey(User)
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

class Document(models.Model):
    document_name = models.CharField(max_length=200)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, blank=True)
    document = models.FileField(upload_to=project_directory_path, max_length=700)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    associated_event = models.ForeignKey(Event, blank=True, null=True)

@receiver(post_save, sender=Board)
def create_states_for_board(sender, instance=None, created=False, **kwargs):
    if created:
        if instance.default == False:
            default_board = Board.objects.get(project = instance.project, default=True)
            states = State.objects.filter(board = default_board)
            for state in states:
                state.pk = None
                state.board = instance
                state.save()

@receiver(post_save, sender=Project)
def create_default_board_for_project(sender, instance=None, created=False, **kwargs):
    if created:
        board = Board(owner=instance.owner, default=True, project=instance, title=instance.name)
        board.save()
        count = 1
        for k, v in STATE_CHOICES:
            state = State(name = v, short_name = k, order = count, board = board)
            state.save()
            count += 1

@receiver(post_save, sender=Ticket)
def add_creator_to_associated_users(sender, instance=None, created=False, **kwargs):
    if created:
        instance.associated_users.add(instance.created_by)

src/ProjectManagementSystem/WebUI/models.py
from django.db import models

# Create your models here.

src/ProjectManagementSystem/WebUI/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from WebAPI.choices import *
from WebAPI.models import *
import re
from django.conf import settings
from django.template.defaultfilters import filesizeformat
from django.utils.translation import ugettext_lazy as _



class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    username.widget.attrs.update({'class' : 'form-control'})
    username.widget.attrs.update({'placeholder' : 'Username'})

    password = forms.CharField(widget = forms.PasswordInput())
    password.widget.attrs.update({'class' : 'form-control'})
    password.widget.attrs.update({'placeholder' : 'Password'})

    def clean_password(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username = username, password = password)
        if not user:
            raise forms.ValidationError("Incorrect username or password.")
        return username

class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=100)
    username.widget.attrs.update({'class' : 'form-control'})
    username.widget.attrs.update({'placeholder' : 'Username'})

    email = forms.EmailField()
    email.widget.attrs.update({'class' : 'form-control'})
    email.widget.attrs.update({'placeholder' : 'Email'})

    password = forms.CharField(widget = forms.PasswordInput())
    password.widget.attrs.update({'class' : 'form-control'})
    password.widget.attrs.update({'placeholder' : 'Password'})

    confirm_password = forms.CharField(widget = forms.PasswordInput())
    confirm_password.widget.attrs.update({'class' : 'form-control'})
    confirm_password.widget.attrs.update({'placeholder' : 'Confirm password'})

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

    def clean_confirm_password(self):
        PASSWORD_REGEX_PATTERN = "^([a-zA-Z0-9]+)+$"
        pattern = re.compile(PASSWORD_REGEX_PATTERN)
        password = self.cleaned_data["password"]
        confirm_password = self.cleaned_data["confirm_password"]

        if not pattern.match(password):
            raise forms.ValidationError("A password can only contain letters from A-Z and digits.")

        if password != confirm_password:
            raise forms.ValidationError("The passwords do not match")

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'visibility']

    name = forms.CharField(max_length=100)
    name.widget.attrs.update({'class' : 'form-control'})

    description = forms.CharField(max_length=1000)
    description.widget.attrs.update({'class' : 'form-control'})

class NewTicketForm(forms.Form):
    name = forms.CharField(max_length=100, required = True)
    name.widget.attrs.update({'class' : 'form-control'})

    priority = forms.ChoiceField(choices = PRIORITY_CHOICES, widget = forms.Select(), required = True, initial ='')
    priority.widget.attrs.update({'class' : 'form-control'})

    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 5,}), max_length=3000, required = False)
    description.widget.attrs.update({'class' : 'form-control'})

    type = forms.ChoiceField(choices = TYPE_CHOICES, widget = forms.Select(), required = True, initial ='' )
    type.widget.attrs.update({'class' : 'form-control'})

    assigned_to = forms.CharField(max_length=100, required = False)
    assigned_to.widget.attrs.update({'class' : 'form-control assigned_to', 'id' : 'assigned_to'})


class ProfileForm(forms.Form):
    username = forms.CharField(max_length=100)
    username.widget.attrs.update({'class' : 'form-control'})

    first_name = forms.CharField(max_length=100)
    first_name.widget.attrs.update({'class' : 'form-control'})

    last_name = forms.CharField(max_length=100)
    last_name.widget.attrs.update({'class' : 'form-control'})

    email = forms.EmailField()
    email.widget.attrs.update({'class' : 'form-control'})

    current_password = forms.CharField(widget = forms.PasswordInput())
    current_password.widget.attrs.update({'class' : 'form-control current_password'})
    current_password.widget.attrs.update({'placeholder' : '********'})

    password = forms.CharField(widget = forms.PasswordInput())
    password.widget.attrs.update({'class' : 'form-control new_password'})
    password.widget.attrs.update({'placeholder' : '********'})

    confirm_password = forms.CharField(widget = forms.PasswordInput())
    confirm_password.widget.attrs.update({'class' : 'form-control new_password'})
    confirm_password.widget.attrs.update({'placeholder' : '********'})

    def clean_confirm_password(self):
        PASSWORD_REGEX_PATTERN = "^([a-zA-Z0-9]+)+$"
        pattern = re.compile(PASSWORD_REGEX_PATTERN)
        password = self.cleaned_data["password"]
        confirm_password = self.cleaned_data["confirm_password"]

        if not pattern.match(password):
            raise forms.ValidationError("A password can only contain letters from A-Z and digits.")

        if password != confirm_password:
            raise forms.ValidationError("The passwords do not match")

class SettingsForm(forms.Form):
    username = forms.CharField(max_length=100)
    username.widget.attrs.update({'class' : 'form-control'})

class DocumentUploadForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('document_name', 'description', 'document', 'project')

    def clean_document(self):
        content = self.cleaned_data['document']
        if content._size > settings.MAX_UPLOAD_SIZE:
            raise forms.ValidationError(_('Please keep filesize under %s. Current filesize %s') % (filesizeformat(settings.MAX_UPLOAD_SIZE), filesizeformat(content._size)))
        return content

class NewEventForm(forms.ModelForm):
    event_title = forms.CharField()
    event_title.widget.attrs.update({'class' : 'form-control event_title'})
    event_title.widget.attrs.update({'id' : 'event_title'})

    start_date = forms.CharField()
    start_date.widget.attrs.update({'class' : 'form-control datepicker start_date'})
    start_date.widget.attrs.update({'id' : 'start_date'})

    end_date = forms.CharField()
    end_date.widget.attrs.update({'class' : 'form-control datepicker end_date'})
    end_date.widget.attrs.update({'id' : 'end_date'})

    type = forms.ChoiceField(choices = EVENT_TYPE_CHOICES, widget = forms.Select(), required = True, initial ='' )
    type.widget.attrs.update({'class' : 'form-control event_type'})
    type.widget.attrs.update({'id' : 'event_type'})

    description = forms.CharField()
    description.widget.attrs.update({'class' : 'form-control event_description'})
    description.widget.attrs.update({'id' : 'event_description'})

    class Meta:
        model = Event
        fields = ('event_title', 'type', 'start_date', 'end_date', 'added_by', 'description', 'project')

class NewStateForm(forms.ModelForm):
    name = forms.CharField()
    name.widget.attrs.update({'class' : 'form-control'})
    name.widget.attrs.update({'id' : 'state_name'})

    short_name = forms.CharField()
    short_name.widget.attrs.update({'class' : 'form-control'})
    short_name.widget.attrs.update({'id' : 'state_short_name'})

    class Meta:
        model = State
        fields = ('name', 'short_name', 'order', 'board')

src/ProjectManagementSystem/WebUI/templates/UI/project/tickets/detail_view.html
{%  extends 'UI/base.html' %}

{% block content %}
{% include 'UI/sidebar.html' %}
<div id="content">
  <div class="container">
    <div class= "row ticket-title">
      {% if messages %}
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissable">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          {{ message }}
        </div>
        {% endfor %}
      {% endif %}
      <div class="heading">
        <h2>{{ticket.short_name}} - {{ ticket.name }}</h2>
      </div>
      <div id="editTicketRow">
        <button id="editTicket" onclick="changeToInputFields()" class="btn btn-default">Edit <span class='glyphicon glyphicon-pencil'></span></button>
        <button id='saveTicket' onclick='saveEdit()' class='btn btn-default'>Save <span class='glyphicon glyphicon-ok'></span></button>
        <button id='cancelEditTicket' onclick='changeToTextFields()' class='btn btn-default'>Cancel <span class='glyphicon glyphicon-remove'></span></button>
        <form action="{% url 'delete_ticket' id=ticket.pk %}" method="POST">
          {% csrf_token %}
          <button onclick="return confirm('Are you sure you want to delete the ticket?')"type="submit" class="btn btn-default">Delete</button>
        </form>
        <a href="#comment" class="btn btn-default"><span class="glyphicon glyphicon-comment"></span> Comment</a>
      </div>
    </div>
    <div class="row ticket-detail-row">
      <h4> Details </h4>
      <hr></hr>
    </div>
    <form id="edit-form" action="{% url 'ticket_detail' slug=ticket.pk %}" method="POST">
    <div class="row">
        {% csrf_token %}
        <div class="col-xs-6 edit-ticket-detail">
          <div class="form-group">
            <label class="ticket-detail-field-label">Title</label> <p id="ticket-name" class="ticket-detail-field field-text">{{ ticket.name }}</p>
            <input name="ticket_name" id="ticket_name" class='form-control input-field' type='text' value='{{ticket.name}}'>
            <br>
          </div>
          <div class="form-group">
            <label class="ticket-detail-field-label">Type</label> <p class="ticket-detail-field field-choice">{{ ticket.get_type_display }}</p>
            <select name="ticket_type" id="ticket_type" class="form-control input-field" id="sel1">
              {% for k, v in type_choices %}
                <option {% if ticket.type == k %} selected {% endif %}>{{ v }}</option>
              {% endfor %}
            </select>
            <br>
          </div>
          <div class="form-group">
            <label class="ticket-detail-field-label" >Priority</label> <p class="ticket-detail-field field-choice">{{ ticket.get_priority_display }}</p>
            <select name="ticket_priority" id="ticket_priority" class="form-control input-field" id="sel1">
              {% for k, v in priority_choices %}
                <option {% if ticket.priority == k %} selected {% endif %}>{{ v }}</option>
              {% endfor %}
            </select>
            <br>
          </div>
          <div class="form-group">
            <label class="ticket-detail-field-label">Status</label> <p class="ticket-detail-field field-choice">{{ ticket.get_state_display }}</p>
            <select name="ticket_state" id="ticket_state" class="form-control input-field" id="sel1">
              {% for state in states %}
                <option {% if ticket.state == state.short_name %} selected {% endif %}>{{ state.name }}</option>
              {% endfor %}
            </select>
            <br>
          </div>
        </div>
        <div class="col-xs-6 edit-ticket-detail">
          <div class="form-group">
            <label class="ticket-detail-field-label">Assigned To</label> <p class="ticket-detail-field field-text">{% if ticket.assigned_to %}{{ticket.assigned_to}}{% else %}Unassigned{% endif %}</p>
            <input name="ticket_assigned_to" id="ticket_name" class='form-control input-field' type='text' value='{% if ticket.assigned_to %}{{ ticket.assigned_to}}{% else %}Unassigned{% endif %}'>
            <br>
          </div>
          <div class="form-group">
            <label class="ticket-detail-field-label">Created On</label> <p class="ticket-detail-field immutable">{{ ticket.created_on }} (UTC)</p><br>
          </div>
          <div class="form-group">
            <label class="ticket-detail-field-label">Last Updated</label> <p class="ticket-detail-field immutable">{{ ticket.last_modified }} (UTC)</p><br>
          </div>
          <div class="form-group">
            <label class="ticket-detail-field-label">Created by</label> <a href="/{{ ticket.created_by.username }}"class="ticket-detail-field immutable">{{ ticket.created_by.get_full_name }}</a><br>
          </div>
        </div>
    </div>
    <div class="row ticket-detail-row">
      <h4> Description </h4>
      <hr></hr>
    </div>
    <div class="row">
      <div class="form-group">
        {% if ticket.description %}
          <p id="description" class="ticket-detail-field"> {{ ticket.description }} </p>
        {% else %}
          <p class="ticket-detail-field"> No description added</p>
        {% endif %}
      </div>
      <textarea name="description" id="description" class="form-control input-field">{{ticket.description}}</textarea>
    </div>
  </form>


    <div class="row ticket-detail-row">
      <h4>Comments</h4>
      <hr></hr>
    </div>
      <form method="POST" action="{% url 'add_comment' pk=ticket.pk %}">
        {% csrf_token %}
      <div class="row">
        <textarea id="comment" name="comment" class="form-control" rows="5" placeholder="Add comment" required></textarea>
      </div>
      <button type="submit" class="btn btn-default">Post</button>
    </form>
    <div id = "comment-section" class ="row">
      {% for comment in comments %}
      <div id = "{{ comment.id }}" name = "article" class="">
        <div class="panel panel-info">
          <div class="panel-body">
            <div class = "col-md-11">
              <p> {{ comment.content }}</p>
              <p> by {{ comment.user }}</p>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
<script>
$(document).ready(function(){
  $('.input-field').hide()
  $('#saveTicket').hide()
  $('#cancelEditTicket').hide()
})


</script>
{% endblock %}

src/ProjectManagementSystem/WebUI/templates/UI/project/tickets/new.html
{%  extends 'UI/base.html' %}

{% block content %}
{% include 'UI/sidebar.html' %}
<div id="content">
  <div class= "row new_project">
    <div class ="container new_project">
      {% if messages %}
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissable">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          {{ message }}
        </div>
        {% endfor %}
      {% endif %}
      <div class="heading">
        <h2>Create a new ticket</h2>
        <p class="heading-description">A project contains all the initial settings needed. Participants can be added manually later or through the automated invitation system.</p>
      </div>
      <hr></hr>
    <form action="{% url 'new_ticket_view' %}" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <div class="form-group">
            <label for="inputName">Ticket Summary:
              <a href="#" data-toggle="tooltip" data-placement="top" title="Looks like this tho!"><span class="glyphicon glyphicon-info-sign"> </span></a>
            </label>
            {{ form.name }}
          </div>
        </div>
        <div class="col-md-6 col-xs-12">
          <div class="form-group">
            <label for="Priority">Priority:
              <a href="#" data-toggle="tooltip" data-placement="top" title="Looks like this tho!"><span class="glyphicon glyphicon-info-sign"> </span></a>
            </label>
            {{ form.priority }}
          </div>
        </div>
        <div class="col-md-6 col-xs-12">
          <div class="form-group">
            <label for="Description">Description:
              <a href="#" data-toggle="tooltip" data-placement="top" title="Looks like this tho!"><span class="glyphicon glyphicon-info-sign"> </span></a>
            </label>
            {{ form.description }}
          </div>
        </div>
        <div class="col-md-6 col-xs-12">
          <div class="form-group">
            <label for="Description">Type:
              <a href="#" data-toggle="tooltip" data-placement="auto top" title="Looks like this tho!"><span class="glyphicon glyphicon-info-sign"> </span></a>
            </label>
            {{ form.type }}
          </div>
        </div>
        <div class="col-md-6 col-xs-12">
          <div class="form-group">
            <label for="Description">Assignee:
              <a href="#" data-toggle="tooltip" data-placement="auto top" title="Looks like this tho!"><span class="glyphicon glyphicon-info-sign"> </span></a>
            </label>
            {{ form.assigned_to }}
          </div>
        </div>
      </div>
      <div class="text-left">
        <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-saved"></i> Create</button>
      </div>
    </form>
    </div>
  </div>
</div>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
    var availableTags = fetchUsersForProject();
});
</script>
{% endblock %}